apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seyoawe-ingress
  namespace: default
  annotations:
    # nginx ingress controller is installed by deploy-manifests.yaml before this is applied.
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seyoawe-engine
                port:
                  number: 8080
